/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pydantic model for create case response.
 * @export
 * @interface CreateCaseResponse
 */
export interface CreateCaseResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCaseResponse
     */
    caseId: string;
}

/**
 * Check if a given object implements the CreateCaseResponse interface.
 */
export function instanceOfCreateCaseResponse(value: object): boolean {
    if (!('caseId' in value)) return false;
    return true;
}

export function CreateCaseResponseFromJSON(json: any): CreateCaseResponse {
    return CreateCaseResponseFromJSONTyped(json, false);
}

export function CreateCaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'caseId': json['case_id'],
    };
}

export function CreateCaseResponseToJSON(value?: CreateCaseResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'case_id': value['caseId'],
    };
}

