/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventDatetime } from './EventDatetime';
import {
    EventDatetimeFromJSON,
    EventDatetimeFromJSONTyped,
    EventDatetimeToJSON,
} from './EventDatetime';

/**
 * Pydantic model for an evidence in a case record.
 * @export
 * @interface EvidenceItem
 */
export interface EvidenceItem {
    /**
     * 
     * @type {string}
     * @memberof EvidenceItem
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof EvidenceItem
     */
    pageNumber: number;
    /**
     * 
     * @type {string}
     * @memberof EvidenceItem
     */
    pdfName: string;
    /**
     * 
     * @type {EventDatetime}
     * @memberof EvidenceItem
     */
    eventDatetime?: EventDatetime;
}

/**
 * Check if a given object implements the EvidenceItem interface.
 */
export function instanceOfEvidenceItem(value: object): boolean {
    if (!('content' in value)) return false;
    if (!('pageNumber' in value)) return false;
    if (!('pdfName' in value)) return false;
    return true;
}

export function EvidenceItemFromJSON(json: any): EvidenceItem {
    return EvidenceItemFromJSONTyped(json, false);
}

export function EvidenceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvidenceItem {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'pageNumber': json['page_number'],
        'pdfName': json['pdf_name'],
        'eventDatetime': json['event_datetime'] == null ? undefined : EventDatetimeFromJSON(json['event_datetime']),
    };
}

export function EvidenceItemToJSON(value?: EvidenceItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'page_number': value['pageNumber'],
        'pdf_name': value['pdfName'],
        'event_datetime': EventDatetimeToJSON(value['eventDatetime']),
    };
}

