/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Evidence
 */
export interface Evidence {
}

/**
 * Check if a given object implements the Evidence interface.
 */
export function instanceOfEvidence(value: object): boolean {
    return true;
}

export function EvidenceFromJSON(json: any): Evidence {
    return EvidenceFromJSONTyped(json, false);
}

export function EvidenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Evidence {
    return json;
}

export function EvidenceToJSON(value?: Evidence | null): any {
    return value;
}

