/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IsComplete
 */
export interface IsComplete {
}

/**
 * Check if a given object implements the IsComplete interface.
 */
export function instanceOfIsComplete(value: object): boolean {
    return true;
}

export function IsCompleteFromJSON(json: any): IsComplete {
    return IsCompleteFromJSONTyped(json, false);
}

export function IsCompleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsComplete {
    return json;
}

export function IsCompleteToJSON(value?: IsComplete | null): any {
    return value;
}

