/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pydantic model for an option in a step in a case record.
 * @export
 * @interface Option
 */
export interface Option {
    /**
     * 
     * @type {string}
     * @memberof Option
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof Option
     */
    text: string;
    /**
     * 
     * @type {boolean}
     * @memberof Option
     */
    selected: boolean;
}

/**
 * Check if a given object implements the Option interface.
 */
export function instanceOfOption(value: object): boolean {
    if (!('key' in value)) return false;
    if (!('text' in value)) return false;
    if (!('selected' in value)) return false;
    return true;
}

export function OptionFromJSON(json: any): Option {
    return OptionFromJSONTyped(json, false);
}

export function OptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Option {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'text': json['text'],
        'selected': json['selected'],
    };
}

export function OptionToJSON(value?: Option | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'text': value['text'],
        'selected': value['selected'],
    };
}

