/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSinceUpdated
 */
export interface TimeSinceUpdated {
}

/**
 * Check if a given object implements the TimeSinceUpdated interface.
 */
export function instanceOfTimeSinceUpdated(value: object): boolean {
    return true;
}

export function TimeSinceUpdatedFromJSON(json: any): TimeSinceUpdated {
    return TimeSinceUpdatedFromJSONTyped(json, false);
}

export function TimeSinceUpdatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSinceUpdated {
    return json;
}

export function TimeSinceUpdatedToJSON(value?: TimeSinceUpdated | null): any {
    return value;
}

