/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pydantic model for a case record.
 * @export
 * @interface Case
 */
export interface Case {
    [key: string]: any | any;
    /**
     * 
     * @type {any}
     * @memberof Case
     */
    caseId: any | null;
    /**
     * 
     * @type {any}
     * @memberof Case
     */
    createdAt: any | null;
    /**
     * 
     * @type {any}
     * @memberof Case
     */
    status?: any;
}

/**
 * Check if a given object implements the Case interface.
 */
export function instanceOfCase(value: object): boolean {
    if (!('caseId' in value)) return false;
    if (!('createdAt' in value)) return false;
    return true;
}

export function CaseFromJSON(json: any): Case {
    return CaseFromJSONTyped(json, false);
}

export function CaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Case {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'caseId': json['case_id'],
        'createdAt': json['created_at'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function CaseToJSON(value?: Case | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'case_id': value['caseId'],
        'created_at': value['createdAt'],
        'status': value['status'],
    };
}

